version: '3'

services:
  web-crawler:
    container_name: web-crawler
    build:
      context: ./crawler
      dockerfile: Dockerfile
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - docker_net

  mongodb:
    container_name: mongodb
    restart: always
    image: mongo:5.0.5
    ports:
     - 27017:27017
    logging:
      options:
        max-size: "50m"
        max-file: "3"
    networks:
      - docker_net
    volumes:
      - db_volume:/data/db

  server:
    container_name: server
    build:
      context: ./server  
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - docker_net

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - docker_net

volumes:
  db_volume:

networks:
  docker_net:
    name: docker_net
    driver: bridge